---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-mall
  namespace: synerunify
  labels:
    app: service-mall
  annotations:
    deployment.kubernetes.io/revision: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-mall
  template:
    metadata:
      labels:
        app: service-mall
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: log
          hostPath:
            path: /data/volume/service-mall/logs
            type: ''
      containers:
        - name: service-mall
          image: 'synerunify/service-mall'
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: synerunify-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: synerunify-config
                  key: REDIS_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: synerunify-config
                  key: LOG_LEVEL
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: log
              mountPath: /logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
...
---
kind: Service
apiVersion: v1
metadata:
  name: service-mall
  namespace: synerunify
  labels:
    app: service-mall
spec:
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 40050
  selector:
    app: service-mall
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
...